### PR TITLE
Stage 2 week 3 (Guide - Part 3)

### PR DESCRIPTION
**Pull request by PeiYingr**
Discord name : 佩瑩☁️

The testable URL : 
http://54.184.227.131:3000/
http://54.184.227.131:3000/attraction/12

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Image slider should extend to full width and keep no margin space with navigator bar in mobile version.

**Comment by PeiYingr** [comment]
Fix the problems below :
> Image slider should extend to full width and keep no margin space with navigator bar in mobile version.

The testable URL : 
http://54.184.227.131:3000/ 
http://54.184.227.131:3000/attraction/12

**Review by cwpeng — CHANGES_REQUESTED** [review]
Image slider should extend to full width and keep no margin space with navigator bar in mobile version.
54 184 227 131_3000_attraction_2

**Comment by PeiYingr** [comment]
Fix the problems below :
> Image slider should keep no margin space with navigator bar in mobile version.

The testable URL :
http://54.184.227.131:3000/
http://54.184.227.131:3000/attraction/12

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
