### PR TITLE
Stage 2 week 2 (Guide - Part 2)

### PR DESCRIPTION
**Pull request by PeiYingr**
Discord 名稱 : 佩瑩☁️

已上線⾴⾯實際可測試網址 :
 http://54.184.227.131:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your code will load the same page multiple times if we scroll down and up quickly. Try testing live URL, not just in your local machine.
2. Left padding of keyword input should not be 0.
3. Search icon is not black.
4. Layout exceed screen width if small to middle devices. There should not exist horizontal scroll bar in any situation.

**Comment by PeiYingr** [comment]
> 1. Your code will load the same page multiple times if we scroll down and up quickly. Try testing live URL, not just in your local machine.
> 2. Left padding of keyword input should not be 0.
> 3. Search icon is not black.
> 4. Layout exceed screen width if small to middle devices. There should not exist horizontal scroll bar in any situation.

**Comment by PeiYingr** [comment]
Fix the problems below :
> 1. Your code will load the same page multiple times if we scroll down and up quickly. Try testing live URL, not just in your local machine.
> 2. Left padding of keyword input should not be 0.
> 3. Search icon is not black.
> 4. Layout exceed screen width if small to middle devices. There should not exist horizontal scroll bar in any situation.

已上線⾴⾯實際可測試網址 :
http://54.184.227.131:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout exceed screen width in middle devices. There should not exist horizontal scroll bar in any situation.

**Comment by PeiYingr** [comment]
Fix the problems below :
> Layout exceed screen width in middle devices. There should not exist horizontal scroll bar in any situation.

The testable URL : http://54.184.227.131:3000/

Sorry, I got the mission wrong because of Figma didn't show the design layout of middle devices.
I'll pay more attention next time.🍀

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
